# Generated by Django 5.2.6 on 2026-01-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_product_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('open_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('dr_cr', models.CharField(choices=[('Dr', 'Dr'), ('Cr', 'Cr')], default='Dr', max_length=2)),
                ('date', models.DateField()),
                ('nozzle_applicable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_used', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'staff_master',
                'ordering': ['staff_name'],
            },
        ),
    ]
