# Generated by Django 5.2.6 on 2026-01-05 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='NozzleAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nozzle_name', models.CharField(max_length=100)),
                ('tank_name', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_used', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nozzle_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_allocations', to='masters.nozzleentry')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzle_allocations', to='masters.staff')),
            ],
            options={
                'db_table': 'staff_nozzle_allocation',
                'ordering': ['nozzle_name'],
                'unique_together': {('staff', 'nozzle_entry')},
            },
        ),
    ]
