# Generated by Django 5.2.6 on 2026-01-05 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_nozzleallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nozzleallocation',
            name='nozzle_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_allocations', to='masters.nozzleentry'),
        ),
        migrations.AlterField(
            model_name='nozzleallocation',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nozzle_allocations', to='masters.staff'),
        ),
    ]
