# Generated by Django 5.2.6 on 2026-01-06 10:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetrolPump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petrol_pump_name', models.CharField(max_length=200, verbose_name='Petrol Pump Name')),
                ('licensee_name', models.CharField(max_length=200, verbose_name='Licensee Name')),
                ('licence_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Licence Number')),
                ('email', models.EmailField(max_length=150, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('mobile_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Enter a valid mobile number', regex='^[0-9]{10,15}$')], verbose_name='Mobile Number')),
                ('email_activation_token', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Petrol Pump',
                'verbose_name_plural': 'Petrol Pumps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PetrolPumpLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP')),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_account', to='accounts.petrolpump')),
            ],
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(db_index=True, max_length=50, verbose_name='Coupon Code')),
                ('is_used', models.BooleanField(default=False)),
                ('verified_on', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('petrol_pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='accounts.petrolpump', verbose_name='Petrol Pump')),
            ],
            options={
                'verbose_name': 'Coupon Code',
                'verbose_name_plural': 'Coupon Codes',
                'ordering': ['-created_at'],
                'unique_together': {('petrol_pump', 'coupon_code')},
            },
        ),
    ]
